version: '3.8'
services:
  db:
    image: postgres:16.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hoax-slasher
    volumes:
      - ./pgdata:/var/lib/postgresql/data #pgdata is local, /var/lib/postgresql/data is in container
      - ./backup:/backup/postgres

  admin:
    image: adminer
    # restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  
  # PRODUCTION
  # nest_be:
  #   build: ./be_antrian
  #   ports:
  #     - '4000:4000'
  #   command: node dist/src/main.js
  #   depends_on:
  #     - db
  #     - rabbitmq
  #   env_file:
  #     - ./be_antrian/.env

  # web-server:
  #   container_name: webserver
  #   image: nginx:stable
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./be_antrian/config:/etc/nginx/conf.d
  #     - /etc/letsencrypt:/etc/letsencrypt:ro
  #     - /tmp/acme_challenge:/tmp/acme_challenge
    
    #END PRODUCTION