version: '3.8'
services:
  db:
    image: postgres:16.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hoax-slasher
    volumes:
      - ./pgdata:/var/lib/postgresql/data #pgdata is local, /var/lib/postgresql/data is in container
      - ./backup:/backup/postgres

  admin:
    image: adminer
    # restart: always
    depends_on:
      - db
    ports:
      - 8080:8080